# Define the docker image to use for the jobs
image: node:18-alpine

# Define the cache to use for the jobs
cache:
  key: ${CI_COMMIT_REF_SLUG}
  paths:
    - ./node_modules/

# Define the stages / jobs for the pipeline
stages:
  - install
  - test

# Install dependencies
install:
  stage: install
  tags: 
    - docker
  script:
    - echo "Installing dependencies..."       # print a message
    - npm install                             # install the dependencies
    - echo "Dependencies installed!"          # print affirmative message

api-test:
  stage: test
  tags:
    - docker
  script:
    - ls                                      # list files in current directory
    - echo "Running tests..."                 # print a message
    - npm run test                            # run postman tests
    - echo "Testing complete!"                # print affirmative message

#TODO: Add MQTT test
mqtt-test:
  stage: test
  tags:
    - docker
  script:
  - echo "This will test the MQTT client"
